#include "DFAFramework.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Passes/PassPlugin.h"

using namespace llvm;

static auto PASS_NAME = "MayPointToAnalysis";
static auto PASS_VERSION = "v0.1";
static auto ARGUMENT_NAME = "";

class PtrInfo {
public:
  /// Interestingly, while the default constructor is never explicitly called,
  /// removing it will result in a compile error
  PtrInfo() {}
  PtrInfo(std::set<std::pair<Value *, Value *>> set) : ptr2val(set) {}

  /// Print definition set for a given statement
  /// Called by `print` method of class `DataFlowAnalysis`
  auto print(Bimap<Instruction *, unsigned> &) -> void {}

  /// Return true if definition sets have the same definitions
  auto operator==(const PtrInfo &other) const -> bool {
    return ptr2val == other.ptr2val;
  }

  /// Meet operator for reaching definition analysis is simply union for
  /// definition set
  auto operator^(const PtrInfo &other) const -> PtrInfo {
    return PtrInfo(set::union2(ptr2val, other.ptr2val));
  }

  std::set<std::pair<Value *, Value *>> ptr2val;
};

class MayPointToAnalysis
    : public DataFlowAnalysis<PtrInfo, AnalysisDirection::Backward> {
public:
  /// Inherit constructor
  using DataFlowAnalysis::DataFlowAnalysis;

  /// Note that the kill set if always empty due to the SSA property.
  /// Thus the output of the transfer function is the union of input and
  /// Definition generated by the current instruction. (if any)
  virtual auto transferFunction(Instruction *instr, PtrInfo input) -> PtrInfo {
    if (auto allocaInstr = dyn_cast<AllocaInst>(instr)) {
      for (auto &op: allocaInstr->operands()) {
        input.ptr2val.insert({op, op});
      }
    }
    return input;
  }
};

namespace {
struct ReachingDefinitionPass : public PassInfoMixin<ReachingDefinitionPass> {
  PreservedAnalyses run(Function &F, FunctionAnalysisManager &) {
    // Instantiate reaching definition analysis with 'top' value of lattice
    auto analysis = MayPointToAnalysis({}, F);

    analysis.run();
    analysis.print();

    return PreservedAnalyses::all();
  }
};
} // namespace

extern "C" ::llvm::PassPluginLibraryInfo LLVM_ATTRIBUTE_WEAK
llvmGetPassPluginInfo() {
  return {LLVM_PLUGIN_API_VERSION, PASS_NAME, PASS_VERSION,
          [](PassBuilder &PB) {
            PB.registerPipelineParsingCallback(
                [](StringRef Name, FunctionPassManager &FPM,
                   ArrayRef<PassBuilder::PipelineElement>) {
                  if (Name == ARGUMENT_NAME) {
                    FPM.addPass(ReachingDefinitionPass());
                    return true;
                  } else {
                    return false;
                  }
                });
          }};
}
